# {{- $name := .Values.bridgeEnvironmentVariables.BRIDGE_BASE_ADDRESS | required ".Values.bridgeEnvironmentVariables.BRIDGE_BASE_ADDRESS is required." -}}
# {{- $name := .Values.bridgeEnvironmentVariables.BRIDGE_USER_AUTH_OIDC_CLIENT_ID | required ".Values.bridgeEnvironmentVariables.BRIDGE_USER_AUTH_OIDC_CLIENT_ID  is required." -}}
# {{- $name := .Values.bridgeEnvironmentVariables.BRIDGE_USER_AUTH_OIDC_ISSUER_URL | required ".Values.bridgeEnvironmentVariables.BRIDGE_USER_AUTH_OIDC_ISSUER_URL is required." -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openshift-console.fullname" . }}
  labels:
    {{- include "openshift-console.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "openshift-console.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "openshift-console.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openshift-console.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.extraEnv }}
              {{- toYaml .Values.extraEnv | nindent 12 }}
            {{- end }}
            # - name: BRIDGE_BASE_ADDRESS
            #   value: {{ .Values.bridgeEnvironmentVariables.BRIDGE_BASE_ADDRESS }}
            # - name: BRIDGE_USER_AUTH
            #   value: {{ .Values.bridgeEnvironmentVariables.BRIDGE_USER_AUTH }}
            # - name: BRIDGE_K8S_AUTH
            #   value: {{ .Values.bridgeEnvironmentVariables.BRIDGE_K8S_AUTH }}
            # - name: BRIDGE_USER_AUTH_OIDC_CLIENT_ID
            #   value: {{ .Values.bridgeEnvironmentVariables.BRIDGE_USER_AUTH_OIDC_CLIENT_ID }}
            # - name: BRIDGE_USER_AUTH_OIDC_CLIENT_SECRET
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ .Values.secret.secretName }}
            #       key: clientSecret
            # - name: BRIDGE_USER_AUTH_OIDC_ISSUER_URL
            #   value: {{ .Values.bridgeEnvironmentVariables.BRIDGE_USER_AUTH_OIDC_ISSUER_URL }}
            # - name: BRIDGE_V
            #   value: {{ .Values.verbosity | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
